title: 徒然なるままにRuby
subtitle: 初心者から上級者までのゆるーいRubyメモ
description: 思いつくままにRubyのトピックをしたためた、初心者から上級者までのブログ
author:
  name   : "Toshio Sekiya"
  avatar : "/assets/images/toshio_a_88x88.png"
  bio    : "Mathmatician/Computer scientist"
  links:
    - label: "はてなブログ"
      icon: "fas fa-pen-nib"
      url: "https://toshiocp.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ToshioCP"

domain: "toshiocp.github.io"
url: "https://toshiocp.github.io"
baseurl: "/Blog-about-Ruby"
github_username: toshiocp

locale: ja
timezone: Asia/Tokyo
lang: ja

search: true

teaser                   : "/assets/images/tsuredure_ruby.png"
logo                     : "/assets/images/toshio_a_88x88.png"
og_image                 : "/assets/images/tsuredure_ruby.png"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: sunrise
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin/
  - .jekyll-cache

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "はてなブログ"
      icon: "fas fa-pen-nib"
      url: "https://toshiocp.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ToshioCP"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
